### ISSUE TITLE
Current leak from MISO, MOSI, CS ?

### ISSUE THREAD

**Issue by baonguyen21** [OPEnSLab-OSU/OPEnS-Power#2]
When the SD card is initialized and the 3V power rail is disconnected, the 3VRAIL seem to still turn on (LED lit up).

Need to probe voltage at MISO, MOSI, CLK, SD to check if there is any current flowing backward to the 3Vrail when the 3V control pin is not activated.

Issue seen from Sitka+ SapFlow.

**Comment by kamocat** [comment]
Yes, you need to start the SPI protocol, or at configure some of those pins as outputs.

**Comment by kamocat** [comment]
Additionally, I would recommend moving the I2C pull-ups to the unswitched 3V3 rail, as they also are dimly powering the LED when pull-ups on the Feather are enabled. This would put them on the same rail as the RTC.

**Comment by nguyenb5** [comment]
Hi Marshal, I read over your message but did not understand well the issue with the I2C Pull-up resistors.

I have not talked to the Loom team but please let us know if you found a way to fix this in software. From Max's testing, the current is leaking from all of the SPI pin including CS. I will start implementing the diode fix to future update, but I do want to sit down and have a chat with you for the board schematic before we purchase anything.

**Comment by kamocat** [comment]
My bad. I misread the schematic, and thought the pullups connected to 3VRail, not 3V3.

**Comment by kamocat** [comment]
Setting the pins as inputs seems to work pretty well.
Just make sure you don't set pin 22 as an output.
Here's an example sketch.
https://gist.github.com/kamocat/b4cf9f0ccbd765f78a6d7390d2da2fe8

**Comment by baonguyen21** [comment]
Hi Marshal, 

Where you able to use this code with Loom?

**Comment by kamocat** [comment]
I haven't tried it with Loom, but I don't see any reason why it wouldn't work.

**Comment by baonguyen21** [comment]
[Updates](https://github.com/OPEnSLab-OSU/OPEnS-Lab-Home/wiki/Hypnos-Updates). A diode has been place between 3v3Rail and the VCC of the SDcard that reduce leakage current down to 1.9uA. 

Diode: [SM5817PL-TP](https://www.digikey.com/product-detail/en/micro-commercial-co/SM5817PL-TP/SM5817PL-TPMSCT-ND/1793410)
