### ISSUE TITLE
Current leak from I2C line

### ISSUE THREAD

**Issue by baonguyen21** [OPEnSLab-OSU/OPEnS-Power#4]
[Hypnos V2.zip](https://github.com/OPEnSLab-OSU/OPEnS-Hypnos/files/4216852/Hypnos.V2.zip)
The current I2C line is pulled up to +3V. Sensors which share the pin will use the power from the I2C line when they are being shut off. For the MMA8451 board, I was getting leakage of 170uA for SCL and 70uA for SDA when the device is off and no communication.

**Comment by kamocat** [comment]
That's strange. I thought the pull-ups were tied to the switched 3V3 rail.

**Comment by baonguyen21** [comment]
not in the current Hypnos V2. We fixed it in Hypnos V2.1.
